name: network_connectivity_troubleshoot
description: A new Flutter package for network connectivity troubleshoot
version: 0.0.2
authors:
  - Bilal Azmat
homepage: https://github.com/bilal-azmat/network_connectivity_troubleshoot

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/images/
